<?php
/** Created by PhpStorm. User: zhangyunpeng  Time:2018/7/11 16:09**/
function printAd($logo){
    echo '<table>';
    echo "<tr><td>{$logo}</td><td>最DIAO古诗社</td></tr>";
    echo '<tr><td>标语</td><td>网址</td></tr>';
    echo '</table>';
}
?>

白日依山尽.....
白日依山尽.....
<?php printAd('啊哈'); ?>
白日依山尽.....
白日依山尽.....
白日依山尽.....
白日依山尽.....
白日依山尽.....
白日依山尽.....
白日依山尽.....
白日依山尽.....
白日依山尽.....
白日依山尽.....
白日依山尽.....
白日依山尽.....

